apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-feed-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: business-feed-project
  template:
    metadata:
      labels:
        app: business-feed-project
    spec:
      containers:
      - name: business-feed-project
        image: schalkg/business-feed-project:latest #Latest image on Docker Hub
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
 name: business-feed-project
spec:
  type: NodePort
  selector:
    app: business-feed-project
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
