export const strings = {
    home: 'Home',
    chat: 'Chat',
    explorer: 'Explorer',
    admin: 'Admin',
    business: 'Business',
    social: 'Social',
    hr: 'HR',
    safety: 'Safety',
    search: 'Search...',
    all: 'all',
    business_filter: 'business',
    social_filter: 'social',
    hr_filter: 'hr',
    safety_filter: 'safety',
};
